[2024-12-14T11:20:11.436+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-14T11:20:11.675+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data.insert_data.insert_data_course manual__2024-12-14T11:20:09.901723+00:00 [queued]>
[2024-12-14T11:20:11.684+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data.insert_data.insert_data_course manual__2024-12-14T11:20:09.901723+00:00 [queued]>
[2024-12-14T11:20:11.685+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-14T11:20:11.702+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_data.insert_data_course> on 2024-12-14 11:20:09.901723+00:00
[2024-12-14T11:20:11.710+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=507) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-14T11:20:11.712+0000] {standard_task_runner.py:63} INFO - Started process 509 to run task
[2024-12-14T11:20:11.713+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_data', 'insert_data.insert_data_course', 'manual__2024-12-14T11:20:09.901723+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/etl_data.py', '--cfg-path', '/tmp/tmpnofcz70w']
[2024-12-14T11:20:11.716+0000] {standard_task_runner.py:91} INFO - Job 101: Subtask insert_data.insert_data_course
[2024-12-14T11:20:11.778+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_data.insert_data.insert_data_course manual__2024-12-14T11:20:09.901723+00:00 [running]> on host 472b63b715e1
[2024-12-14T11:20:11.892+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data' AIRFLOW_CTX_TASK_ID='insert_data.insert_data_course' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T11:20:09.901723+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-14T11:20:09.901723+00:00'
[2024-12-14T11:20:11.894+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-14T11:20:12.317+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-14T11:20:12.319+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-14T11:20:12.339+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_data, task_id=insert_data.insert_data_course, run_id=manual__2024-12-14T11:20:09.901723+00:00, execution_date=20241214T112009, start_date=20241214T112011, end_date=20241214T112012
[2024-12-14T11:20:12.370+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-14T11:20:12.421+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-14T11:20:12.423+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
