[2024-12-19T04:28:33.846+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-19T04:28:34.307+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT_instruction_fact_data.load_to_clickhouse.load_clickhouse_instruction_aggregate manual__2024-12-19T04:25:50.989861+00:00 [queued]>
[2024-12-19T04:28:34.442+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT_instruction_fact_data.load_to_clickhouse.load_clickhouse_instruction_aggregate manual__2024-12-19T04:25:50.989861+00:00 [queued]>
[2024-12-19T04:28:34.442+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-19T04:28:34.849+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_clickhouse.load_clickhouse_instruction_aggregate> on 2024-12-19 04:25:50.989861+00:00
[2024-12-19T04:28:35.040+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8541) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-19T04:28:35.063+0000] {standard_task_runner.py:63} INFO - Started process 8560 to run task
[2024-12-19T04:28:35.079+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ELT_instruction_fact_data', 'load_to_clickhouse.load_clickhouse_instruction_aggregate', 'manual__2024-12-19T04:25:50.989861+00:00', '--job-id', '1227', '--raw', '--subdir', 'DAGS_FOLDER/elt_instruction_fact.py', '--cfg-path', '/tmp/tmpsbyd5_s5']
[2024-12-19T04:28:35.112+0000] {standard_task_runner.py:91} INFO - Job 1227: Subtask load_to_clickhouse.load_clickhouse_instruction_aggregate
[2024-12-19T04:28:35.803+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT_instruction_fact_data.load_to_clickhouse.load_clickhouse_instruction_aggregate manual__2024-12-19T04:25:50.989861+00:00 [running]> on host 33a17f71e955
[2024-12-19T04:28:38.832+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ELT_instruction_fact_data' AIRFLOW_CTX_TASK_ID='load_to_clickhouse.load_clickhouse_instruction_aggregate' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T04:25:50.989861+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T04:25:50.989861+00:00'
[2024-12-19T04:28:38.843+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-19T04:28:52.376+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-19T04:28:52.376+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/fit_task.py", line 157, in load_to_clickhouse
    clickhouse_client.execute(f"""
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 382, in execute
    rv = self.process_ordinary_query(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 580, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 213, in receive_result
    return result.get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 229, in packet_generator
    packet = self.receive_packet()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 246, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 999.
Coordination::Exception. Coordination::Exception: Coordination error: Operation timeout, path /clickhouse/task_queue/ddl/query-. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000d1d323b
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000817ab6c
2. DB::Exception::Exception<char const*, String const&>(int, FormatStringHelperImpl<std::type_identity<char const*>::type, std::type_identity<String const&>::type>, char const*&&, String const&) @ 0x000000000ff7af4b
3. Coordination::Exception::fromPath(Coordination::Error, String const&) @ 0x000000000ff7a4a8
4. zkutil::ZooKeeper::createAncestors(String const&) @ 0x00000000136ce5ff
5. DB::DDLWorker::enqueueQueryAttempt(DB::DDLLogEntry&) @ 0x000000001130d04d
6. DB::DDLWorker::enqueueQuery(DB::DDLLogEntry&, DB::ZooKeeperRetriesInfo const&, std::shared_ptr<DB::QueryStatus>) @ 0x000000001130cbd7
7. DB::executeDDLQueryOnCluster(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, DB::DDLQueryOnClusterParams const&) @ 0x0000000011c6a5eb
8. DB::InterpreterCreateQuery::executeQueryOnCluster(DB::ASTCreateQuery&) @ 0x000000001168d6b2
9. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x0000000011689be6
10. DB::InterpreterCreateQuery::execute() @ 0x000000001169a770
11. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000011c7cea6
12. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000011c77fdb
13. DB::TCPHandler::runImpl() @ 0x0000000012eb85be
14. DB::TCPHandler::run() @ 0x0000000012ed1df8
15. Poco::Net::TCPServerConnection::start() @ 0x0000000015d89527
16. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015d899b9
17. Poco::PooledThread::run() @ 0x0000000015d563fc
18. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015d5499d
19. ? @ 0x0000709c529fbac3
20. ? @ 0x0000709c52a8ca04

[2024-12-19T04:28:52.552+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ELT_instruction_fact_data, task_id=load_to_clickhouse.load_clickhouse_instruction_aggregate, run_id=manual__2024-12-19T04:25:50.989861+00:00, execution_date=20241219T042550, start_date=20241219T042834, end_date=20241219T042852
[2024-12-19T04:28:53.872+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1227 for task load_to_clickhouse.load_clickhouse_instruction_aggregate (Code: 999.
Coordination::Exception. Coordination::Exception: Coordination error: Operation timeout, path /clickhouse/task_queue/ddl/query-. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000d1d323b
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000817ab6c
2. DB::Exception::Exception<char const*, String const&>(int, FormatStringHelperImpl<std::type_identity<char const*>::type, std::type_identity<String const&>::type>, char const*&&, String const&) @ 0x000000000ff7af4b
3. Coordination::Exception::fromPath(Coordination::Error, String const&) @ 0x000000000ff7a4a8
4. zkutil::ZooKeeper::createAncestors(String const&) @ 0x00000000136ce5ff
5. DB::DDLWorker::enqueueQueryAttempt(DB::DDLLogEntry&) @ 0x000000001130d04d
6. DB::DDLWorker::enqueueQuery(DB::DDLLogEntry&, DB::ZooKeeperRetriesInfo const&, std::shared_ptr<DB::QueryStatus>) @ 0x000000001130cbd7
7. DB::executeDDLQueryOnCluster(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, DB::DDLQueryOnClusterParams const&) @ 0x0000000011c6a5eb
8. DB::InterpreterCreateQuery::executeQueryOnCluster(DB::ASTCreateQuery&) @ 0x000000001168d6b2
9. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x0000000011689be6
10. DB::InterpreterCreateQuery::execute() @ 0x000000001169a770
11. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000011c7cea6
12. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000011c77fdb
13. DB::TCPHandler::runImpl() @ 0x0000000012eb85be
14. DB::TCPHandler::run() @ 0x0000000012ed1df8
15. Poco::Net::TCPServerConnection::start() @ 0x0000000015d89527
16. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015d899b9
17. Poco::PooledThread::run() @ 0x0000000015d563fc
18. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015d5499d
19. ? @ 0x0000709c529fbac3
20. ? @ 0x0000709c52a8ca04
; 8560)
[2024-12-19T04:28:56.052+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-19T04:28:56.091+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-19T04:28:58.102+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
