[2024-12-14T10:46:31.583+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-14T10:46:31.824+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data.insert_data.insert_data_program manual__2024-12-14T10:46:26.937418+00:00 [queued]>
[2024-12-14T10:46:31.846+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data.insert_data.insert_data_program manual__2024-12-14T10:46:26.937418+00:00 [queued]>
[2024-12-14T10:46:31.847+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-14T10:46:31.870+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_data.insert_data_program> on 2024-12-14 10:46:26.937418+00:00
[2024-12-14T10:46:31.885+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=407) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-14T10:46:31.888+0000] {standard_task_runner.py:63} INFO - Started process 409 to run task
[2024-12-14T10:46:31.891+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_data', 'insert_data.insert_data_program', 'manual__2024-12-14T10:46:26.937418+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/etl_data.py', '--cfg-path', '/tmp/tmp_1s5vrw5']
[2024-12-14T10:46:31.895+0000] {standard_task_runner.py:91} INFO - Job 88: Subtask insert_data.insert_data_program
[2024-12-14T10:46:31.968+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_data.insert_data.insert_data_program manual__2024-12-14T10:46:26.937418+00:00 [running]> on host 06cbf31e97a5
[2024-12-14T10:46:32.115+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data' AIRFLOW_CTX_TASK_ID='insert_data.insert_data_program' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T10:46:26.937418+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-14T10:46:26.937418+00:00'
[2024-12-14T10:46:32.117+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-14T10:46:32.444+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-14T10:46:32.445+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-14T10:46:32.464+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_data, task_id=insert_data.insert_data_program, run_id=manual__2024-12-14T10:46:26.937418+00:00, execution_date=20241214T104626, start_date=20241214T104631, end_date=20241214T104632
[2024-12-14T10:46:32.505+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-14T10:46:32.556+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-14T10:46:32.557+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
