[2024-12-14T10:49:18.717+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-14T10:49:18.903+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data.insert_data.rename_directories manual__2024-12-14T10:48:51.875688+00:00 [queued]>
[2024-12-14T10:49:18.911+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data.insert_data.rename_directories manual__2024-12-14T10:48:51.875688+00:00 [queued]>
[2024-12-14T10:49:18.911+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-14T10:49:18.924+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_data.rename_directories> on 2024-12-14 10:48:51.875688+00:00
[2024-12-14T10:49:18.931+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=534) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-14T10:49:18.933+0000] {standard_task_runner.py:63} INFO - Started process 536 to run task
[2024-12-14T10:49:18.940+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_data', 'insert_data.rename_directories', 'manual__2024-12-14T10:48:51.875688+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/etl_data.py', '--cfg-path', '/tmp/tmpzkiwniff']
[2024-12-14T10:49:18.946+0000] {standard_task_runner.py:91} INFO - Job 119: Subtask insert_data.rename_directories
[2024-12-14T10:49:19.010+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_data.insert_data.rename_directories manual__2024-12-14T10:48:51.875688+00:00 [running]> on host 06cbf31e97a5
[2024-12-14T10:49:19.153+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data' AIRFLOW_CTX_TASK_ID='insert_data.rename_directories' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T10:48:51.875688+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-14T10:48:51.875688+00:00'
[2024-12-14T10:49:19.154+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-14T10:49:19.157+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-14T10:49:19.159+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-14T10:49:19.172+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_data, task_id=insert_data.rename_directories, run_id=manual__2024-12-14T10:48:51.875688+00:00, execution_date=20241214T104851, start_date=20241214T104918, end_date=20241214T104919
[2024-12-14T10:49:19.228+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-14T10:49:19.262+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-14T10:49:19.263+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
